"""remove field filename

Revision ID: 3490b7d45d96
Revises: 2f41039a5434
Create Date: 2025-09-28 17:48:27.566914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3490b7d45d96'
down_revision = '2f41039a5434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
